# APP
export APP_NAME=darwin-app
export APP_DISTRIBUTION=xenial
export APP_ARCH=all
export BUILD_LATEST=true
#export PRODUCT_VERSION=1.1.0SNAPSHOT

# Play! Framework
export PLAY_VERSION=1.4.4

# Redmine
export REDMINE_URL=
export REDMINE_TOKEN=
export REDMINE_PROJECT=paths-play-module
export REDMINE_GLOBAL_RELEASE_PAGE=Release_Management

# Artifactory
export ARTIFACTORY_TOKEN=
export ARTIFACTORY_APT_REPO=apt-4pf-transversals